{{cookiecutter.project_slug}}/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.http import HttpResponse

from {{ cookiecutter.project_slug }}.views import PricingView

urlpatterns = [
    url(
        r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'
    ),
    url(
        r'^health_check/$',
        lambda r: HttpResponse("ok"),
    ),
    url(
        r'^terms-and-conditions/$',
        TemplateView.as_view(template_name='pages/terms_and_conditions.html'),
        name='terms_and_conditions'
    ),
    url(
        r'^privacy-policy/$',
        TemplateView.as_view(template_name='pages/privacy_policy.html'),
        name='privacy_policy'
    ),
    url(
        r'^pricing/$',
        PricingView.as_view(),
        name='pricing'
    ),
    url(
        r'^features/$',
        TemplateView.as_view(template_name='pages/features.html'),
        name='features'
    ),
    # Django Admin, use {% raw %}{% url 'admin:index' %}{% endraw %}
    url(
        settings.ADMIN_URL,
        include(admin.site.urls)
    ),
    {% if cookiecutter.react == "yes" %}
    url(
        r'^api/',
        include('{{ cookiecutter.project_slug }}.api.urls', namespace="api")
    ),
    {% endif %}
    url(
        r'^auth/',
        include('allauth.urls')
    ),
    {% if cookiecutter.blog == "yes" %}
    url(
        r'^blog/',
        include('{{ cookiecutter.project_slug }}.blog.urls', namespace="blog"),
    ),
    url(r'^tinymce/', include('tinymce.urls')),
    {% endif %}
    url(
        r'^app/',
        include('{{ cookiecutter.project_slug }}.app.urls', namespace="app"),
    ),
    {% if cookiecutter.private_beta == "yes" %}
    url(
        r'^beta/',
        include('{{ cookiecutter.project_slug }}.beta.urls', namespace="beta"),
    ),
    {% endif %}
    url(r'^users/',
        include('{{ cookiecutter.project_slug }}.users.urls', namespace='users')),
    url(r"^payments/", include("{{ cookiecutter.project_slug }}.payments.urls")),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(
            r'^400/$',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}
        ),
        url(
            r'^403/$',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}
        ),
        url(
            r'^404/$',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}
        ),
        url(r'^500/$', default_views.server_error),
    ]

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf.urls import include, url

urlpatterns = [
    url(
        r'^v1/',
        include('{{ cookiecutter.project_slug }}.api.v1.urls', namespace="v1"),
    ),
]

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/app/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url

from {{ cookiecutter.project_slug }}.app import views

urlpatterns = [
    url(
        r'^$',
        views.DashboardView.as_view(),
        name='dashboard'
    ),
]

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/beta/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^request-invite/$',
        view=views.RequestInviteView.as_view(),
        name='request-invite'
    ),
    url(
        regex=r'^request-success/$',
        view=views.RequestInviteSuccess.as_view(),
        name='request-success'
    ),
]

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/beta/models.py
from model_utils.models import TimeStampedModel

from django.db import models
from django.utils.crypto import get_random_string
from django.utils.encoding import python_2_unicode_compatible

def get_code():
    return get_random_string(50)


@python_2_unicode_compatible
class Invite(TimeStampedModel):

    code = models.CharField(max_length=50, default=get_code)
    request = models.OneToOneField("Request")

    def __str__(self):
        return self.code


@python_2_unicode_compatible
class Request(TimeStampedModel):

    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/blog/models.py
from model_utils.models import TimeStampedModel
from autoslug import AutoSlugField
from slugify import slugify as unicode_slugify
from tinymce.models import HTMLField

from django.db import models
from django.core.urlresolvers import reverse
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Entry(TimeStampedModel):

    title = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from='title',
                         slugify=unicode_slugify)
    content = HTMLField()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:entry", kwargs={"slug": self.slug})

    class Meta:
        ordering = ("-created",)

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/beta/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from {{ cookiecutter.project_slug }}.beta.models import Request

class InviteForm(forms.Form):

    code = forms.CharField(max_length=50, min_length=50)


class RequestForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(RequestForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit('submit', 'Submit'))

    class Meta:
        model = Request
        fields = ("email",)

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/api/v1/views.py
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated
from rest_framework import status

from {{ cookiecutter.project_slug }}.api.v1 import serializer as serializers

class CurrentUserView(APIView):

    permission_classes = (IsAuthenticated,)

    def get(self, request):
        serializer = serializers.UserSerializer(request.user)
        return Response(serializer.data)

    def put(self, request):
        serializer = serializers.UserSerializer(request.user, data=request.data)
        if request.data and serializer.is_valid():
            serializer.save()
            return Response(serializer.data)
        return Response({}, status=status.HTTP_400_BAD_REQUEST)

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/app/views.py
from django.views.generic import TemplateView


class DashboardView(TemplateView):

    template_name = "app/dashboard.html"

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/beta/views.py
from allauth.utils import build_absolute_uri

from django.views.generic import CreateView, TemplateView
from django.core.mail import mail_admins
from django.core.urlresolvers import reverse

from {{ cookiecutter.project_slug }}.beta.models import Request
from {{ cookiecutter.project_slug }}.beta.forms import RequestForm

class RequestInviteView(CreateView):
    model = Request
    form_class = RequestForm

    def get_success_url(self):
        return reverse("beta:request-success")

    def form_valid(self, form):
        mail_admins(
            subject="Invite requested",
            message="{email} requested an invite to your beta.\n\n"
                    "Manage invites at {admin_url}".format(
                        email=form.cleaned_data["email"],
                        admin_url=build_absolute_uri(None, "/foo")
                    )
        )
        return super(RequestInviteView, self).form_valid(form)


class RequestInviteSuccess(TemplateView):
    template_name = "beta/request_success.html"

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/blog/views.py
from django.views.generic import ListView, DetailView

from {{ cookiecutter.project_slug }}.blog.models import Entry


class EntryListView(ListView):

    model = Entry
    context_object_name = "entries"
    paginate_by = 5


class EntryView(DetailView):

    model = Entry
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/payments/views.py
import logging
import jwt
from jwt.exceptions import DecodeError
from stripe.error import StripeError, CardError
from stripe import Customer as StripeCustomer

from pinax.stripe.models import Customer
from pinax.stripe.actions.customers import sync_customer
from pinax.stripe.views import PaymentMethodCreateView, SubscriptionUpdateView, PaymentMethodUpdateView
from pinax.stripe.actions.sources import sync_payment_source_from_stripe_data, delete_card
from pinax.stripe.mixins import LoginRequiredMixin

from django import forms
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.utils.encoding import smart_str
from django.conf import settings
from django.views.generic import FormView
from django.shortcuts import redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.http import HttpResponseRedirect

from {{ cookiecutter.project_slug }}.payments.plan import get_plans

logger = logging.getLogger(__name__)


class CustomSubscriptionUpdateView(SubscriptionUpdateView):

    def get_context_data(self, **kwargs):
        data = super(CustomSubscriptionUpdateView, self).get_context_data(**kwargs)
        data["plans"] = get_plans()
        data["change_button"] = True
        return data

    def update_subscription(self, plan_id):
        super(CustomSubscriptionUpdateView, self).update_subscription(plan_id)
        #deactivate_exceeding_private_repos.delay(self.request.user.pk)


class CustomPaymentMethodCreateView(PaymentMethodCreateView):

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        if self.customer is None:
            messages.error(request, "You can't add a card without a subscription")
            return HttpResponseRedirect(reverse("pinax_stripe_subscription_list"))
        return super(CustomPaymentMethodCreateView, self).dispatch(request, *args, **kwargs)

    def create_card(self, stripe_token):
        for card in self.customer.card_set.all():
            delete_card(self.customer, card.stripe_id)
        source = self.customer.stripe_customer.sources.create(source=stripe_token)
        sync_payment_source_from_stripe_data(self.customer, source)

    def post(self, request, *args, **kwargs):
        try:
            self.create_card(request.POST.get("stripeToken"))
            return redirect("pinax_stripe_subscription_list")
        except CardError as e:
            return self.render_to_response(self.get_context_data(errors=smart_str(e)))


class OctobatForm(forms.Form):

    transactionDetails = forms.CharField()

    def clean_transactionDetails(self):
        details = self.cleaned_data["transactionDetails"]
        try:
            data = jwt.decode(details, settings.OCTOBAT_PRIVATE_KEY)
            customer = data["customer_id"]
            return data
        except DecodeError as e:
            logger.error("Unable to clean transactionDetails for data: {}".format(
                details
            ), exc_info=True)
            raise forms.ValidationError("transaction details could'nt be received")
        except KeyError as e:
            logger.error("Unable to clean transactionDetails for data: {}".format(
                details
            ), exc_info=True)
            raise forms.ValidationError("transaction details could'nt be received")


class CheckoutView(LoginRequiredMixin, FormView):

    form_class = OctobatForm
    template_name = "pinax/stripe/subscription_create.html"

    def get_context_data(self, **kwargs):
        data = super(CheckoutView, self).get_context_data(**kwargs)
        data["plans"] = get_plans()
        data["OCTOBAT_PUBLIC_KEY"] = settings.OCTOBAT_PUBLIC_KEY
        data["OCTOBAT_SUPPLIER_NAME"] = settings.OCTOBAT_SUPPLIER_NAME
        data["OCTOBAT_IMAGE"] = settings.OCTOBAT_IMAGE
        data["octobat_button"] = True
        return data

    def form_valid(self, form):
        trans = form.cleaned_data["transactionDetails"]
        try:
            stripe_customer = StripeCustomer.retrieve(trans["customer_id"])
            cus = Customer.objects.create(
                user=self.request.user,
                stripe_id=stripe_customer["id"]
            )
            sync_customer(cus, stripe_customer)
            return redirect(reverse("pinax_stripe_subscription_list"))
        except StripeError as e:
            messages.error(self.request, "Unable to communicate with stripe. Please try again later")
            logger.error("Stripe Error during checkout for customer {}".format(
                self.request.user
            ), exc_info=True)
            return redirect(reverse("pinax_stripe_subscription_list"))

    def form_invalid(self, form):
        messages.error(self.request,
                       "Unable to process request. Please contact support.")
        return super(CheckoutView, self).form_invalid(form)

    def dispatch(self, request, *args, **kwargs):
        if not self.request.user.is_anonymous():
            if self.request.user.is_customer:
                messages.add_message(request, messages.ERROR, "You already have a subscription")
                return redirect(reverse("pinax_stripe_subscription_list"))
        return super(CheckoutView, self).dispatch(request, *args, **kwargs)

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/users/views.py
from braces.views import LoginRequiredMixin

from django.core.urlresolvers import reverse
from django.views.generic import UpdateView

from .models import User


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:update')

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(pk=self.request.user.pk)

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/views.py
from django.views.generic import TemplateView

from {{ cookiecutter.project_slug }}.payments.plan import get_plans


class PricingView(TemplateView):

    template_name = "pages/pricing.html"

    def get_context_data(self, **kwargs):
        data = super(PricingView, self).get_context_data(**kwargs)
        data["plans"] = get_plans(free_plan=True)
        data["col"] = "col-md-{}".format(int(12 / len(data["plans"]))) if len(data["plans"]) else "col-md-4"
        return data

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/templates/base.html
{% raw %}{% load staticfiles i18n compress %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
    <meta name="robots" content="{% block robots %}noindex,follow{% endblock %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="{% static 'images/favicon.png' %}">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    {% block css %}
    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">
    {% endcompress %}
    {% compress css %}
    <link href="{% static 'css/main.css' %}" rel="stylesheet">
    {% endcompress %}
    {% endblock %}
    {% block css_extra %}
    {% endblock %}

  </head>

  <body class="{% block body_class %}{% endblock %}">
    {% block body %}
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">
            <img src="{% static 'images/logo.png' %}"/>
          </a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url "features" %}">Features</a></li>
            <li><a href="{% url "pricing" %}">Pricing</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if request.user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url "app:dashboard" %}">Account</a>
                </li>
              {% else %}
                <li class="nav-item">
                  <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
                </li>
                <li class="nav-item">
                  <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
                </li>
              {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>


    <div class="container content">
      {% block content %}

      {% endblock content %}
    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}
    <footer class="footer">
      <div class="container">
        <p class="text-muted">
          {% endraw %}{% if cookiecutter.blog == "yes" %}{% raw %}<a href="{% url "blog:entries" %}">Blog</a>{% endraw %}{% endif %}{% raw %}
          <span class="pull-right">
            <a href="{% url "privacy_policy" %}">Privacy Policy</a> | <a href="{% url "terms_and_conditions" %}">Terms and Conditions</a>
          </span>
        </p>
      </div>
    </footer>
    {% endblock body %}
    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Latest JQuery -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/bootstrap.js' %}"></script>
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}
    {% endblock javascript %}
    {% block javascript_extra %}
    {% endblock %}
  </body>
</html>{% endraw %}

{{cookiecutter.project_slug}}/{{ cookiecutter.project_slug }}/templates/blank_base.html
{% raw %}{% extends "base.html" %}
{% load static %}

{% block body_class %}blank{% endblock %}

{% block body %}
  <div class="container">
    {% block logo %}
      <div class="row">
        <div class="col-md-4 col-md-offset-4 col-sm-10 col-sm-offset-1">
          <a href="{% url "home" %}">
            <img src="{% static "images/logo.png" %}" class="img img-responsive"/>
          </a>
        </div>
      </div>
    {% endblock %}
    <div class="content">
    {% block content %}

    {% endblock %}
    </div>
  </div>
{% endblock %}{% endraw %}